name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Set up goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      # First authenticate with the auth action
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # Then set up the gcloud CLI
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "go build"
        run: go build -o notely .

      # Build and push Docker image
      - name: "Build and push Docker image"
        run: "gcloud builds submit --project notely-461222 --tag us-central1-docker.pkg.dev/notely-461222/notely-ar-repo/notely-app:latest ."

      - name: run migrations
        run: chmod +x ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-461222/notely-ar-repo/notely-app:latest --region us-central1 --allow-unauthenticated --project notely-461222 --max-instances=4
